# Generated by Django 5.1.7 on 2025-03-24 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('tablet', 'Tablet'), ('smartphone', 'Smartphone'), ('keyboard', 'Keyboard'), ('pen', 'Pen'), ('pos', 'POS')], max_length=20)),
                ('model', models.CharField(choices=[('TL10', 'TL10'), ('TL12', 'TL12'), ('T307G', 'T307G'), ('T307F', 'T307F')], max_length=20)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('odm', models.CharField(choices=[('ZTECH', 'ZTECH'), ('EPUDO', 'EPUDO'), ('HENA', 'HENA')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
